FROM runatlantis/atlantis:latest

ARG TERRAGRUNT_VERSION=0.58.7

RUN curl -fsSL -o /usr/local/bin/terragrunt \
    "https://github.com/gruntwork-io/terragrunt/releases/download/v${TERRAGRUNT_VERSION}/terragrunt_linux_amd64" \
    && chmod +x /usr/local/bin/terragrunt
